"use client";

import React, { createContext, useContext, useState } from "react";

export type LangCode = "en" | "hi" | "bn" | "ta" | "te" | "mr";

export const LANGUAGES: { code: LangCode; label: string; nativeLabel: string }[] = [
  { code: "en", label: "English",  nativeLabel: "English"   },
  { code: "hi", label: "Hindi",    nativeLabel: "हिन्दी"    },
  { code: "bn", label: "Bengali",  nativeLabel: "বাংলা"     },
  { code: "ta", label: "Tamil",    nativeLabel: "தமிழ்"     },
  { code: "te", label: "Telugu",   nativeLabel: "తెలుగు"    },
  { code: "mr", label: "Marathi",  nativeLabel: "मराठी"     },
];

export type Translations = {
  appName: string;
  welcome: string;
  welcomeSub: string;
  getStarted: string;
  dashboard: string;
  learning: string;
  quiz: string;
  resources: string;
  constituency: string;
  constitution: string;
  currentFocusArea: string;
  lockedToIndia: string;
  educationalPath: string;
  registration: string;
  certification: string;
  takeQuiz: string;
  glossary: string;
  startLearning: string;
  resumeLearning: string;
  overallProgress: string;
  howVotingWorks: string;
  launchSimulation: string;
  learningModules: string;
  whyItMatters: string;
  actionSteps: string;
  advancedDetails: string;
  completeAndContinue: string;
  nextModule: string;
  finishAndTakeQuiz: string;
  constitutionalBasis: string;
  findYourConstituency: string;
  enterPincode: string;
  search: string;
  yourConstituency: string;
  yourRepresentative: string;
  electionResults: string;
  deepDive: string;
  democraticFramework: string;
  learningMilestones: string;
  ready: string;
  helpCenter: string;
  dataPrivacy: string;
  glossaryMenu: string;
  currentStageLabel: string;
  overallStatus: string;
  courseContent: string;
  hrs: string;
  simulation: string;
  launchNow: string;
  viewAll: string;
  active: string;
  doneLabel: string;
  civicLiteracyBadgeEarned: string;
  retakeQuiz: string;
  viewTimeline: string;
  question: string;
  of: string;
  correct: string;
  notQuite: string;
  finishQuiz: string;
  skipForNow: string;
  submitAnswer: string;
  nextQuestion: string;
  viewResults: string;
  electionGuideProgress: string;
  stage: string;
  viewFullCurriculum: string;
  glossaryCorner: string;
  studyTip: string;
  howCanWeHelp: string;
  askNow: string;
  faqTitle: string;
  quickCheck: string;
  proTip: string;
  stillHaveQuestions: string;
  speakToAmbassador: string;
  terminologyGlossary: string;
  filterTerms: string;
  downloadPdf: string;
};

const T: Record<LangCode, Translations> = {
  en: {
    appName: "CivicGuide",
    welcome: "Welcome to CivicGuide",
    welcomeSub: "Your trusted guide to democratic participation in India.",
    getStarted: "Get Started",
    dashboard: "Dashboard",
    learning: "Learning",
    quiz: "Quiz",
    resources: "Resources",
    constituency: "Constituency",
    constitution: "Constitution",
    currentFocusArea: "CURRENT FOCUS AREA",
    lockedToIndia: "Resources are exclusively tailored for the Indian Electoral System.",
    educationalPath: "Your Educational Path",
    registration: "Registration",
    certification: "Certification",
    takeQuiz: "Take Quiz",
    glossary: "Glossary & FAQ",
    startLearning: "Start Learning",
    resumeLearning: "Resume Learning",
    overallProgress: "Overall Progress",
    howVotingWorks: "How Voting Works",
    launchSimulation: "Launch Simulation",
    learningModules: "Learning Modules",
    whyItMatters: "Why It Matters",
    actionSteps: "Action Steps",
    advancedDetails: "Advanced Details",
    completeAndContinue: "Complete & Continue",
    nextModule: "Next Module",
    finishAndTakeQuiz: "Finish & Take Quiz",
    constitutionalBasis: "Constitutional Basis",
    findYourConstituency: "Find Your Constituency",
    enterPincode: "Enter your 6-digit Pincode",
    search: "Search",
    yourConstituency: "Your Constituency",
    yourRepresentative: "Your Representative",
    electionResults: "2024 Election Results",
    deepDive: "Deep Dive",
    democraticFramework: "Democratic Framework",
    learningMilestones: "LEARNING MILESTONES",
    ready: "READY",
    helpCenter: "Help Center",
    dataPrivacy: "Data Privacy",
    glossaryMenu: "Glossary",
    currentStageLabel: "Current Stage",
    overallStatus: "Overall Status",
    courseContent: "Course Content",
    hrs: "hrs",
    simulation: "Simulation",
    launchNow: "Launch now",
    viewAll: "View All",
    active: "Active",
    doneLabel: "Done",
    civicLiteracyBadgeEarned: "Civic Literacy Badge Earned!",
    retakeQuiz: "Retake Quiz",
    viewTimeline: "View Timeline",
    question: "Question",
    of: "of",
    correct: "Correct!",
    notQuite: "Not quite.",
    finishQuiz: "Finish Quiz",
    skipForNow: "Skip for now",
    submitAnswer: "Submit Answer",
    nextQuestion: "Next Question",
    viewResults: "View Results",
    electionGuideProgress: "Election Guide Progress",
    stage: "STAGE",
    viewFullCurriculum: "View Full Curriculum",
    glossaryCorner: "Glossary Corner",
    studyTip: "Study Tip",
    howCanWeHelp: "How can we help you participate?",
    askNow: "Ask Now",
    faqTitle: "Frequently Asked Questions",
    quickCheck: "QUICK CHECK",
    proTip: "PRO TIP",
    stillHaveQuestions: "Still have questions?",
    speakToAmbassador: "Speak to an Ambassador",
    terminologyGlossary: "Terminology Glossary",
    filterTerms: "Filter terms...",
    downloadPdf: "Download Full PDF Glossary",
  },
  hi: {
    appName: "सिविकगाइड",
    welcome: "सिविकगाइड में आपका स्वागत है",
    welcomeSub: "भारत में लोकतांत्रिक भागीदारी के लिए आपका विश्वसनीय मार्गदर्शक।",
    getStarted: "शुरू करें",
    dashboard: "डैशबोर्ड",
    learning: "सीखना",
    quiz: "प्रश्नोत्तरी",
    resources: "संसाधन",
    constituency: "निर्वाचन क्षेत्र",
    constitution: "संविधान",
    currentFocusArea: "वर्तमान क्षेत्र",
    lockedToIndia: "संसाधन विशेष रूप से भारतीय चुनाव प्रणाली के लिए तैयार किए गए हैं।",
    educationalPath: "आपका शैक्षिक मार्ग",
    registration: "पंजीकरण",
    certification: "प्रमाणन",
    takeQuiz: "प्रश्नोत्तरी दें",
    glossary: "शब्दकोश और FAQ",
    startLearning: "सीखना शुरू करें",
    resumeLearning: "सीखना जारी रखें",
    overallProgress: "समग्र प्रगति",
    howVotingWorks: "मतदान कैसे होता है",
    launchSimulation: "सिमुलेशन लॉन्च करें",
    learningModules: "शिक्षण मॉड्यूल",
    whyItMatters: "यह क्यों महत्वपूर्ण है",
    actionSteps: "कार्य चरण",
    advancedDetails: "उन्नत विवरण",
    completeAndContinue: "पूर्ण करें और जारी रखें",
    nextModule: "अगला मॉड्यूल",
    finishAndTakeQuiz: "समाप्त करें और प्रश्नोत्तरी दें",
    constitutionalBasis: "संवैधानिक आधार",
    findYourConstituency: "अपना निर्वाचन क्षेत्र खोजें",
    enterPincode: "अपना 6 अंकों का पिनकोड दर्ज करें",
    search: "खोजें",
    yourConstituency: "आपका निर्वाचन क्षेत्र",
    yourRepresentative: "आपके प्रतिनिधि",
    electionResults: "2024 चुनाव परिणाम",
    deepDive: "गहन अध्ययन",
    democraticFramework: "लोकतांत्रिक ढांचा",
    learningMilestones: "शिक्षण मील के पत्थर",
    ready: "तैयार",
    helpCenter: "सहायता केंद्र",
    dataPrivacy: "डेटा गोपनीयता",
    glossaryMenu: "शब्दकोश",
    currentStageLabel: "वर्तमान चरण",
    overallStatus: "कुल स्थिति",
    courseContent: "पाठ्यक्रम सामग्री",
    hrs: "घंटे",
    simulation: "सिमुलेशन",
    launchNow: "अभी लॉन्च करें",
    viewAll: "सभी देखें",
    active: "सक्रिय",
    doneLabel: "हो गया",
    civicLiteracyBadgeEarned: "नागरिक साक्षरता बैज अर्जित!",
    retakeQuiz: "पुनः प्रयास करें",
    viewTimeline: "समयरेखा देखें",
    question: "प्रश्न",
    of: "का",
    correct: "सही!",
    notQuite: "काफी नहीं।",
    finishQuiz: "प्रश्नोत्तरी समाप्त करें",
    skipForNow: "अभी छोड़ें",
    submitAnswer: "उत्तर सबमिट करें",
    nextQuestion: "अगला प्रश्न",
    viewResults: "परिणाम देखें",
    electionGuideProgress: "चुनाव गाइड प्रगति",
    stage: "चरण",
    viewFullCurriculum: "पूर्ण पाठ्यक्रम देखें",
    glossaryCorner: "शब्दकोश कोना",
    studyTip: "अध्ययन टिप",
    howCanWeHelp: "हम आपकी भागीदारी में कैसे मदद कर सकते हैं?",
    askNow: "अभी पूछें",
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    quickCheck: "त्वरित जाँच",
    proTip: "प्रो टिप",
    stillHaveQuestions: "क्या आपके पास अभी भी प्रश्न हैं?",
    speakToAmbassador: "राजदूत से बात करें",
    terminologyGlossary: "शब्दावली शब्दकोश",
    filterTerms: "शर्तें फ़िल्टर करें...",
    downloadPdf: "पूर्ण PDF शब्दकोश डाउनलोड करें",
  },
  bn: {
    appName: "সিভিকগাইড",
    welcome: "সিভিকগাইডে স্বাগতম",
    welcomeSub: "ভারতে গণতান্ত্রিক অংশগ্রহণের জন্য আপনার বিশ্বস্ত গাইড।",
    getStarted: "শুরু করুন",
    dashboard: "ড্যাশবোর্ড",
    learning: "শিক্ষা",
    quiz: "কুইজ",
    resources: "সম্পদ",
    constituency: "নির্বাচনী এলাকা",
    constitution: "সংবিধান",
    currentFocusArea: "বর্তমান ফোকাস এলাকা",
    lockedToIndia: "সম্পদ ভারতীয় নির্বাচনী ব্যবস্থার জন্য বিশেষভাবে তৈরি।",
    educationalPath: "আপনার শিক্ষামূলক পথ",
    registration: "নিবন্ধন",
    certification: "সার্টিফিকেশন",
    takeQuiz: "কুইজ দিন",
    glossary: "শব্দকোষ ও FAQ",
    startLearning: "শেখা শুরু করুন",
    resumeLearning: "শেখা চালিয়ে যান",
    overallProgress: "সামগ্রিক অগ্রগতি",
    howVotingWorks: "ভোটিং কিভাবে কাজ করে",
    launchSimulation: "সিমুলেশন চালু করুন",
    learningModules: "শিক্ষামূলক মডিউল",
    whyItMatters: "এটি কেন গুরুত্বপূর্ণ",
    actionSteps: "পদক্ষেপ",
    advancedDetails: "উন্নত বিবরণ",
    completeAndContinue: "সম্পূর্ণ করুন এবং চালিয়ে যান",
    nextModule: "পরবর্তী মডিউল",
    finishAndTakeQuiz: "শেষ করুন এবং কুইজ দিন",
    constitutionalBasis: "সাংবিধানিক ভিত্তি",
    findYourConstituency: "আপনার নির্বাচনী এলাকা খুঁজুন",
    enterPincode: "আপনার ৬ সংখ্যার পিনকোড দিন",
    search: "অনুসন্ধান",
    yourConstituency: "আপনার নির্বাচনী এলাকা",
    yourRepresentative: "আপনার প্রতিনিধি",
    electionResults: "২০২৪ নির্বাচনের ফলাফল",
    deepDive: "গভীর অধ্যয়ন",
    democraticFramework: "গণতান্ত্রিক কাঠামো",
    learningMilestones: "শিক্ষার মাইলফলক",
    ready: "প্রস্তুত",
    helpCenter: "সহায়তা কেন্দ্র",
    dataPrivacy: "ডেটা গোপনীয়তা",
    glossaryMenu: "শব্দকোষ",
    currentStageLabel: "বর্তমান পর্যায়",
    overallStatus: "সামগ্রিক অবস্থা",
    courseContent: "পাঠ্যক্রমের বিষয়বস্তু",
    hrs: "ঘণ্টা",
    simulation: "সিমুলেশন",
    launchNow: "এখনই শুরু করুন",
    viewAll: "সব দেখুন",
    active: "সক্রিয়",
    doneLabel: "সম্পন্ন",
    civicLiteracyBadgeEarned: "নাগরিক সাক্ষরতা ব্যাজ অর্জিত!",
    retakeQuiz: "আবার কুইজ দিন",
    viewTimeline: "টাইমলাইন দেখুন",
    question: "প্রশ্ন",
    of: "এর",
    correct: "সঠিক!",
    notQuite: "একদম নয়।",
    finishQuiz: "কুইজ শেষ করুন",
    skipForNow: "এখনকার মতো বাদ দিন",
    submitAnswer: "উত্তর জমা দিন",
    nextQuestion: "পরবর্তী প্রশ্ন",
    viewResults: "ফলাফল দেখুন",
    electionGuideProgress: "নির্বাচন গাইড অগ্রগতি",
    stage: "পর্যায়",
    viewFullCurriculum: "সম্পূর্ণ পাঠ্যক্রম দেখুন",
    glossaryCorner: "শব্দকোষ কর্নার",
    studyTip: "পড়ার টিপ",
    howCanWeHelp: "আমরা আপনাকে অংশগ্রহণে কীভাবে সাহায্য করতে পারি?",
    askNow: "এখনই জিজ্ঞাসা করুন",
    faqTitle: "সচরাচর জিজ্ঞাস্য প্রশ্নাবলী",
    quickCheck: "দ্রুত পরীক্ষা",
    proTip: "প্রো টিপ",
    stillHaveQuestions: "এখনও প্রশ্ন আছে?",
    speakToAmbassador: "একজন রাষ্ট্রদূতের সাথে কথা বলুন",
    terminologyGlossary: "পরিভাষা শব্দকোষ",
    filterTerms: "শর্তাবলী ফিল্টার করুন...",
    downloadPdf: "সম্পূর্ণ PDF শব্দকোষ ডাউনলোড করুন",
  },
  ta: {
    appName: "சிவிக்கைடு",
    welcome: "சிவிக்கைடுக்கு வரவேற்கிறோம்",
    welcomeSub: "இந்தியாவில் ஜனநாயக பங்கேற்புக்கான உங்கள் நம்பகமான வழிகாட்டி.",
    getStarted: "தொடங்குங்கள்",
    dashboard: "டாஷ்போர்டு",
    learning: "கற்றல்",
    quiz: "வினாடி வினா",
    resources: "வளங்கள்",
    constituency: "தொகுதி",
    constitution: "அரசியலமைப்பு",
    currentFocusArea: "தற்போதைய கவனப் பகுதி",
    lockedToIndia: "வளங்கள் இந்திய தேர்தல் முறைக்காக மட்டுமே.",
    educationalPath: "உங்கள் கல்வி பாதை",
    registration: "பதிவு",
    certification: "சான்றிதழ்",
    takeQuiz: "வினாடி வினா எடு",
    glossary: "சொற்களஞ்சியம் & FAQ",
    startLearning: "கற்றலை தொடங்கு",
    resumeLearning: "கற்றலை தொடர்",
    overallProgress: "ஒட்டுமொத்த முன்னேற்றம்",
    howVotingWorks: "வாக்களிப்பு எவ்வாறு செயல்படுகிறது",
    launchSimulation: "உருவகப்படுத்தலை தொடங்கு",
    learningModules: "கற்றல் தொகுதிகள்",
    whyItMatters: "ஏன் முக்கியம்",
    actionSteps: "நடவடிக்கை படிகள்",
    advancedDetails: "மேம்பட்ட விவரங்கள்",
    completeAndContinue: "முடித்து தொடர்",
    nextModule: "அடுத்த தொகுதி",
    finishAndTakeQuiz: "முடித்து வினாடி வினா எடு",
    constitutionalBasis: "அரசியலமைப்பு அடிப்படை",
    findYourConstituency: "உங்கள் தொகுதியை கண்டறியுங்கள்",
    enterPincode: "உங்கள் 6 இலக்க பின்கோடை உள்ளிடுங்கள்",
    search: "தேடு",
    yourConstituency: "உங்கள் தொகுதி",
    yourRepresentative: "உங்கள் பிரதிநிதி",
    electionResults: "2024 தேர்தல் முடிவுகள்",
    deepDive: "ஆழமான ஆய்வு",
    democraticFramework: "ஜனநாயகக் கட்டமைப்பு",
    learningMilestones: "கற்றல் மைல்கற்கள்",
    ready: "தயார்",
    helpCenter: "உதவி மையம்",
    dataPrivacy: "தரவு தனியுரிமை",
    glossaryMenu: "சொற்களஞ்சியம்",
    currentStageLabel: "தற்போதைய நிலை",
    overallStatus: "ஒட்டுமொத்த நிலை",
    courseContent: "பாட உள்ளடக்கம்",
    hrs: "மணி",
    simulation: "உருவகப்படுத்துதல்",
    launchNow: "இப்போதே தொடங்கு",
    viewAll: "அனைத்தையும் காண்க",
    active: "செயலில்",
    doneLabel: "முடிந்தது",
    civicLiteracyBadgeEarned: "குடிமை கல்வியறிவு பேட்ஜ் பெறப்பட்டது!",
    retakeQuiz: "மீண்டும் வினாடி வினா எடு",
    viewTimeline: "காலவரிசையை காண்க",
    question: "கேள்வி",
    of: "இல்",
    correct: "சரி!",
    notQuite: "சரியல்ல.",
    finishQuiz: "வினாடி வினாவை முடி",
    skipForNow: "இப்போதைக்குத் தவிர்க்கவும்",
    submitAnswer: "பதிலைச் சமர்ப்பி",
    nextQuestion: "அடுத்த கேள்வி",
    viewResults: "முடிவுகளைக் காண்க",
    electionGuideProgress: "தேர்தல் வழிகாட்டி முன்னேற்றம்",
    stage: "நிலை",
    viewFullCurriculum: "முழு பாடத்திட்டத்தையும் காண்க",
    glossaryCorner: "சொற்களஞ்சிய மூலை",
    studyTip: "படிப்பு குறிப்பு",
    howCanWeHelp: "நீங்கள் பங்கேற்க நாங்கள் எவ்வாறு உதவலாம்?",
    askNow: "இப்போதே கேளுங்கள்",
    faqTitle: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    quickCheck: "விரைவான சோதனை",
    proTip: "சார்பு குறிப்பு",
    stillHaveQuestions: "இன்னும் கேள்விகள் உள்ளதா?",
    speakToAmbassador: "ஒரு தூதரிடம் பேசுங்கள்",
    terminologyGlossary: "சொற்களஞ்சியம்",
    filterTerms: "சொற்களை வடிகட்டவும்...",
    downloadPdf: "முழு PDF சொற்களஞ்சியத்தைப் பதிவிறக்கவும்",
  },
  te: {
    appName: "సివిక్‌గైడ్",
    welcome: "సివిక్‌గైడ్‌కు స్వాగతం",
    welcomeSub: "భారతదేశంలో ప్రజాస్వామ్య భాగస్వామ్యానికి మీ విశ్వసనీయ మార్గదర్శి.",
    getStarted: "ప్రారంభించండి",
    dashboard: "డ్యాష్‌బోర్డ్",
    learning: "నేర్చుకోవడం",
    quiz: "క్విజ్",
    resources: "వనరులు",
    constituency: "నియోజకవర్గం",
    constitution: "రాజ్యాంగం",
    currentFocusArea: "ప్రస్తుత దృష్టి ప్రాంతం",
    lockedToIndia: "వనరులు భారతీయ ఎన్నికల వ్యవస్థ కోసం ప్రత్యేకంగా రూపొందించబడ్డాయి.",
    educationalPath: "మీ విద్యా మార్గం",
    registration: "నమోదు",
    certification: "ధృవీకరణ",
    takeQuiz: "క్విజ్ తీసుకోండి",
    glossary: "నిఘంటువు & FAQ",
    startLearning: "నేర్చుకోవడం ప్రారంభించండి",
    resumeLearning: "నేర్చుకోవడం కొనసాగించండి",
    overallProgress: "మొత్తం పురోగతి",
    howVotingWorks: "ఓటింగ్ ఎలా పని చేస్తుంది",
    launchSimulation: "సిమ్యులేషన్ ప్రారంభించండి",
    learningModules: "అభ్యాస మాడ్యూళ్ళు",
    whyItMatters: "ఎందుకు ముఖ్యమైనది",
    actionSteps: "చర్య దశలు",
    advancedDetails: "అధునాతన వివరాలు",
    completeAndContinue: "పూర్తి చేసి కొనసాగించండి",
    nextModule: "తదుపరి మాడ్యూల్",
    finishAndTakeQuiz: "పూర్తి చేసి క్విజ్ తీసుకోండి",
    constitutionalBasis: "రాజ్యాంగ ఆధారం",
    findYourConstituency: "మీ నియోజకవర్గాన్ని కనుగొనండి",
    enterPincode: "మీ 6 అంకెల పిన్‌కోడ్ నమోదు చేయండి",
    search: "వెతకండి",
    yourConstituency: "మీ నియోజకవర్గం",
    yourRepresentative: "మీ ప్రతినిధి",
    electionResults: "2024 ఎన్నికల ఫలితాలు",
    deepDive: "లోతైన అధ్యయనం",
    democraticFramework: "ప్రజాస్వామ్య చట్రం",
    learningMilestones: "అభ్యాస మైలురాళ్ళు",
    ready: "సిద్ధం",
    helpCenter: "సహాయ కేంద్రం",
    dataPrivacy: "డేటా గోప్యత",
    glossaryMenu: "నిఘంటువు",
    currentStageLabel: "ప్రస్తుత దశ",
    overallStatus: "మొత్తం స్థితి",
    courseContent: "కోర్సు కంటెంట్",
    hrs: "గంటలు",
    simulation: "సిమ్యులేషన్",
    launchNow: "ఇప్పుడే ప్రారంభించు",
    viewAll: "అన్నీ చూడండి",
    active: "క్రియాశీల",
    doneLabel: "పూర్తయింది",
    civicLiteracyBadgeEarned: "పౌర అక్షరాస్యత బ్యాడ్జ్ సంపాదించారు!",
    retakeQuiz: "క్విజ్ మళ్ళీ తీసుకోండి",
    viewTimeline: "టైమ్‌లైన్ చూడండి",
    question: "ప్రశ్న",
    of: "లో",
    correct: "సరియైనది!",
    notQuite: "కాదు.",
    finishQuiz: "క్విజ్ పూర్తి చేయండి",
    skipForNow: "ప్రస్తుతానికి వదిలివేయండి",
    submitAnswer: "సమాధానం సమర్పించండి",
    nextQuestion: "తదుపరి ప్రశ్న",
    viewResults: "ఫలితాలు చూడండి",
    electionGuideProgress: "ఎన్నికల మార్గదర్శి పురోగతి",
    stage: "దశ",
    viewFullCurriculum: "పూర్తి పాఠ్యప్రణాళిక చూడండి",
    glossaryCorner: "నిఘంటువు మూల",
    studyTip: "అధ్యయన చిట్కా",
    howCanWeHelp: "మీరు పాల్గొనడానికి మేము ఎలా సహాయపడగలము?",
    askNow: "ఇప్పుడే అడగండి",
    faqTitle: "తరచుగా అడిగే ప్రశ్నలు",
    quickCheck: "శీఘ్ర తనిఖీ",
    proTip: "ప్రో చిట్కా",
    stillHaveQuestions: "ఇంకా ప్రశ్నలు ఉన్నాయా?",
    speakToAmbassador: "ఒక అంబాసిడర్‌తో మాట్లాడండి",
    terminologyGlossary: "పరిభాష నిఘంటువు",
    filterTerms: "పదాలను ఫిల్టర్ చేయండి...",
    downloadPdf: "పూర్తి PDF నిఘంటువును డౌన్‌లోడ్ చేయండి",
  },
  mr: {
    appName: "सिविकगाइड",
    welcome: "सिविकगाइडमध्ये स्वागत आहे",
    welcomeSub: "भारतातील लोकशाही सहभागासाठी तुमचा विश्वासू मार्गदर्शक.",
    getStarted: "सुरू करा",
    dashboard: "डॅशबोर्ड",
    learning: "शिकणे",
    quiz: "प्रश्नमंजुषा",
    resources: "संसाधने",
    constituency: "मतदारसंघ",
    constitution: "संविधान",
    currentFocusArea: "सध्याचे लक्ष केंद्र",
    lockedToIndia: "संसाधने भारतीय निवडणूक प्रणालीसाठी विशेषतः तयार केली आहेत.",
    educationalPath: "तुमचा शैक्षणिक मार्ग",
    registration: "नोंदणी",
    certification: "प्रमाणन",
    takeQuiz: "प्रश्नमंजुषा द्या",
    glossary: "शब्दकोश व FAQ",
    startLearning: "शिकणे सुरू करा",
    resumeLearning: "शिकणे सुरू ठेवा",
    overallProgress: "एकूण प्रगती",
    howVotingWorks: "मतदान कसे होते",
    launchSimulation: "सिम्युलेशन सुरू करा",
    learningModules: "शिक्षण मॉड्यूल",
    whyItMatters: "हे का महत्त्वाचे आहे",
    actionSteps: "कृती पायऱ्या",
    advancedDetails: "प्रगत तपशील",
    completeAndContinue: "पूर्ण करा आणि पुढे जा",
    nextModule: "पुढील मॉड्यूल",
    finishAndTakeQuiz: "समाप्त करा आणि प्रश्नमंजुषा द्या",
    constitutionalBasis: "घटनात्मक आधार",
    findYourConstituency: "तुमचा मतदारसंघ शोधा",
    enterPincode: "तुमचा 6 अंकी पिनकोड टाका",
    search: "शोधा",
    yourConstituency: "तुमचा मतदारसंघ",
    yourRepresentative: "तुमचे प्रतिनिधी",
    electionResults: "2024 निवडणूक निकाल",
    deepDive: "सखोल अभ्यास",
    democraticFramework: "लोकशाही संरचना",
    learningMilestones: "शिक्षण टप्पे",
    ready: "तयार",
    helpCenter: "मदत केंद्र",
    dataPrivacy: "डेटा गोपनीयता",
    glossaryMenu: "शब्दकोश",
    currentStageLabel: "सध्याचा टप्पा",
    overallStatus: "एकूण स्थिती",
    courseContent: "अभ्यासक्रम मजकूर",
    hrs: "तास",
    simulation: "सिम्युलेशन",
    launchNow: "आत्ता सुरू करा",
    viewAll: "सर्व पहा",
    active: "सक्रिय",
    doneLabel: "झाले",
    civicLiteracyBadgeEarned: "नागरी साक्षरता बॅज प्राप्त!",
    retakeQuiz: "प्रश्नमंजुषा पुन्हा द्या",
    viewTimeline: "वेळापत्रक पहा",
    question: "प्रश्न",
    of: "पैकी",
    correct: "बरोबर!",
    notQuite: "नाही.",
    finishQuiz: "प्रश्नमंजुषा समाप्त करा",
    skipForNow: "सध्या वगळा",
    submitAnswer: "उत्तर सबमिट करा",
    nextQuestion: "पुढील प्रश्न",
    viewResults: "निकाल पहा",
    electionGuideProgress: "निवडणूक मार्गदर्शक प्रगती",
    stage: "टप्पा",
    viewFullCurriculum: "पूर्ण अभ्यासक्रम पहा",
    glossaryCorner: "शब्दकोश कोपरा",
    studyTip: "अभ्यास टीप",
    howCanWeHelp: "आम्ही तुम्हाला सहभागी होण्यास कशी मदत करू शकतो?",
    askNow: "आत्ता विचारा",
    faqTitle: "वारंवार विचारले जाणारे प्रश्न",
    quickCheck: "त्वरीत तपास",
    proTip: "प्रो टीप",
    stillHaveQuestions: "अद्याप प्रश्न आहेत का?",
    speakToAmbassador: "राजदूताशी बोला",
    terminologyGlossary: "शब्दावली शब्दकोश",
    filterTerms: "शब्द फिल्टर करा...",
    downloadPdf: "पूर्ण PDF शब्दकोश डाउनलोड करा",
  },
};

interface LanguageContextValue {
  lang: LangCode;
  setLang: (l: LangCode) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: "en",
  setLang: () => {},
  t: T.en,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<LangCode>("en");
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: T[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
